### ISSUE TITLE
Issue with fetch() JSON

### ISSUE THREAD

**Issue by pawan-live** [pawan-live/lecture-timetable-app#14]
Cannot get the fetched object into the js file. Probably a syntax error. Hard-coded the JSON data to the main.js file for a temporary fix.

**Comment by pawan-live** [comment]
code is in the fetching-json branch.
If you fork & clone, please run "git branch -a" to view all remote branches and "git checkout branch-name" to open the branch in your local repo

**Comment by yokemanann** [comment]
The reason is you are trying to read the local file by using `fetch` api which Chrome is not allowed to do so.
Checkout this: [fetch api cannot load, url scheme 'file' is not supported](https://stackoverflow.com/questions/69144759/fetch-api-cannot-load-url-scheme-file-is-not-supported)

You may achieve it by installing "Live Server" extension in VSCode, then click this button: ![image](https://user-images.githubusercontent.com/52019912/156478701-33c174ca-d01a-4305-a608-e9a1d46c49a5.png)

In your code, change `fetch("./table.json")` to `fetch("http://127.0.0.1:5500/table.json")` and it should work
